/**
 * ASP Hook Bridge Extension
 *
 * Generated by Agent Spaces - DO NOT EDIT
 *
 * This extension bridges hooks.toml declarations to Pi event handlers,
 * executing shell scripts with standardized ASP_* environment variables.
 */

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const LOG_DIR = path.join(os.homedir(), 'praesidium', 'var', 'logs');
const LOG_FILE = path.join(LOG_DIR, 'asp-hooks.log');

function log(level, message) {
  try {
    fs.mkdirSync(LOG_DIR, { recursive: true });
    const timestamp = new Date().toISOString();
    fs.appendFileSync(LOG_FILE, `[${timestamp}] [${level}] ${message}\n`);
  } catch (e) {
    // Silently fail if logging fails
  }
}

module.exports = function(pi) {
  log('INFO', 'ASP Hook Bridge loaded');

  // Hook: sessionstart -> /Users/lherron/praesidium/under-construction/asp-pisdk-harness/asp_modules/ralph-plan/pi/hooks-scripts/scripts/agent_motd.sh
  pi.on('session_start', async (event, ctx) => {
    const toolsFilter = ["startup"];
    // For tool events, filter by tool name
    if (toolsFilter && event.toolName && !toolsFilter.includes(event.toolName)) {
      return;
    }

    const env = {
      ...process.env,
      ASP_TOOL_NAME: event.toolName || '',
      ASP_TOOL_ARGS: JSON.stringify(event.input || {}),
      ASP_TOOL_RESULT: JSON.stringify(event.result || {}),
      ASP_HARNESS: 'pi',
      ASP_SPACES: "praesidium-defaults",
    };

    try {
      log('DEBUG', `Running hook: /Users/lherron/praesidium/under-construction/asp-pisdk-harness/asp_modules/ralph-plan/pi/hooks-scripts/scripts/agent_motd.sh`);
      const { spawn } = await import('node:child_process');
      let payload = '';
      try {
        payload = JSON.stringify(event ?? {});
      } catch {
        payload = '';
      }
      const proc = spawn('/Users/lherron/praesidium/under-construction/asp-pisdk-harness/asp_modules/ralph-plan/pi/hooks-scripts/scripts/agent_motd.sh', [], {
        env,
        stdio: ['pipe', 'pipe', 'pipe'],
        shell: true,
      });
      let stdout = '';
      let stderr = '';
      proc.stdout?.on('data', (data) => {
        stdout += data.toString();
      });
      proc.stderr?.on('data', (data) => {
        stderr += data.toString();
      });
      if (proc.stdin) {
        proc.stdin.write(payload);
        proc.stdin.end();
      }
      const exitCode = await new Promise((resolve) => proc.on('close', resolve));
      const outputParts = [];
      if (stdout.trim().length > 0) {
        outputParts.push(stdout.trimEnd());
      }
      if (stderr.trim().length > 0) {
        outputParts.push(`[stderr]\n${stderr.trimEnd()}`);
      }
      if (outputParts.length > 0 || exitCode !== 0) {
        const header = `Hook sessionstart: /Users/lherron/praesidium/under-construction/asp-pisdk-harness/asp_modules/ralph-plan/pi/hooks-scripts/scripts/agent_motd.sh`;
        const body = outputParts.length > 0 ? outputParts.join('\n\n') : '(no output)';
        const content = `${header}\n\n${body}`;
        const options = ctx.isIdle() ? {} : { deliverAs: 'nextTurn' };
        pi.sendMessage(
          {
            customType: 'asp-hook',
            content,
            display: true,
            details: {
              event: 'sessionstart',
              script: '/Users/lherron/praesidium/under-construction/asp-pisdk-harness/asp_modules/ralph-plan/pi/hooks-scripts/scripts/agent_motd.sh',
              exitCode,
            },
          },
          options
        );
      }
      if (exitCode !== 0) {
        log('WARN', `Hook script "/Users/lherron/praesidium/under-construction/asp-pisdk-harness/asp_modules/ralph-plan/pi/hooks-scripts/scripts/agent_motd.sh" exited with ${exitCode}`);
      } else {
        log('DEBUG', `Hook script "/Users/lherron/praesidium/under-construction/asp-pisdk-harness/asp_modules/ralph-plan/pi/hooks-scripts/scripts/agent_motd.sh" completed successfully`);
      }
    } catch (err) {
      log('ERROR', `Hook script "/Users/lherron/praesidium/under-construction/asp-pisdk-harness/asp_modules/ralph-plan/pi/hooks-scripts/scripts/agent_motd.sh" failed: ${err}`);
    }
  });
};
